### ISSUE TITLE
Break on String interpolation

### ISSUE THREAD

**Issue by BloodSucker123** [davidrios/pug-tmbundle#24] opened 2018-08-27 00:17 UTC
I'm using Sublime Text 3 on Mac OS.
![screen shot 2018-08-27 at 8 15 01 am](https://user-images.githubusercontent.com/41031355/44634836-57bc0900-a9d1-11e8-9119-b457fe00e7e9.png)

But when I add semicolon it works. But the problem is the semicolon will be included on the generated file.

![screen shot 2018-08-27 at 8 16 36 am](https://user-images.githubusercontent.com/41031355/44634858-8df98880-a9d1-11e8-8a14-a2d9b0d64bbb.png)

Do you have any idea on how to fix this?

**Comment by hit1205** [comment] 2019-04-06 19:46
I have same problem after I upgraded Sublime Text 3 from 3.1.1 to 3.2 (Windows 7)

**Comment by hit1205** [comment] 2019-04-06 19:56
Duplicate of #22 

It seems the same problem, the color is correct if I disable the JavaScript package

**Comment by hit1205** [comment] 2019-04-06 19:58
Duplicate of #22

**Closed as not planned** 2022-12-02 01:00 UTC
Labels: duplicate
